#!/bin/bash
if [ -z "$API_KEY" ]; then
  echo "API_KEY is not configured"
  exit 1
fi

if [ -z "$API_SECRET" ]; then
  echo "API_SECRET is not configured"
  exit 1
fi

if [ -z "$PASSPHRASE" ]; then
  echo "PASSPHRASE is not configured"
  exit 1
fi

if [ -z "$USER" ]; then
  echo "PASSPHRASE is not configured"
  exit 1
fi

if [ -z "$FQDN" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

PLATFORM_URL="https://$FQDN"

if [ -z "$1" ]; then
  echo "usage: courier scheduler create-job <FILE>"
  exit 1;
fi

if test -f "$1"; then
    export STATUS="OK"
else
  echo "file $1 not found"
  exit 1;
fi


curl -s -H "api-key: $API_KEY" -H "api-secret: $API_SECRET" -X POST -H "Content-Type: application/json" -d @$1 $PLATFORM_URL/jobs