#!/bin/bash
if [ -z "$PLATFORM_URL" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi


if [ -z "$1" ]; then
  echo "usage: courier scheduler estimate-schedule <UUID> <COUNT>"
  exit 0;
fi


if [ $(curl -LI -X HEAD -H "api-key: $API_KEY" -H "api-secret: $API_SECRET" $PLATFORM_URL/job/$1 -o /dev/null -w '%{http_code}\n' -s) == "200" ]; then 
  export IMMEDIATE=$(curl -s -H "api-key: $API_KEY" -H "api-secret: $API_SECRET" $PLATFORM_URL/job/$1 | jq '.immediate')

  if [ "$IMMEDIATE" == "true" ]; then
    echo "can not esimate a schedule for an immediate job"
  else
    if [ -z "$2" ]; then
      curl -s -H "api-key: $API_KEY" -H "api-secret: $API_SECRET" $PLATFORM_URL/job/$1/estimate?count=10 | jq
    else
      curl -s -H "api-key: $API_KEY" -H "api-secret: $API_SECRET" $PLATFORM_URL/job/$1/estimate?count=$2 | jq
    fi
  fi
fi

