#!/bin/bash
if [ -z "$API_KEY" ]; then
  echo "API_KEY is not configured"
  exit 1
fi

if [ -z "$API_SECRET" ]; then
  echo "API_SECRET is not configured"
  exit 1
fi

if [ -z "$PASSPHRASE" ]; then
  echo "PASSPHRASE is not configured"
  exit 1
fi

if [ -z "$USER" ]; then
  echo "PASSPHRASE is not configured"
  exit 1
fi

if [ -z "$FQDN" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

PLATFORM_URL="https://$FQDN"

if [ -z "$1" ]; then
  echo "usage: node node get-node <UUID>"
  exit 0;
fi

if [ $1 == "--help" ]; then
    echo "usage: node node get-node <UUID>"
    echo "Flags"
    echo "--help"
    echo "--json"
    exit 0
fi

if [ "$2" == "--json" ]; then
  curl -s -H "api-key: $API_KEY" -H "api-secret: $API_SECRET" $PLATFORM_URL/v1/nodes/$1 | jq
  exit 0
fi

if [ "$2" == "--help" ]; then
    echo "usage: node node get-node $1"
    echo "Flags"
    echo "--help"
    echo "--json"
    exit 0
fi

if [ -z "$1" ]; then
    export status="OK"
else
  curl -s -H "api-key: $API_KEY" -H "api-secret: $API_SECRET" $PLATFORM_URL/v1/nodes/$1 | jq '{ id: .id, hostname: (.attributes[] | select(.name=="hostname") | .value)}'
  exit 0;
fi

