#!/bin/bash
export CMD=""
if [ -z "$API_KEY" ]; then
  echo "API_KEY is not configured"
  exit 1
fi

if [ -z "$API_SECRET" ]; then
  echo "API_SECRET is not configured"
  exit 1
fi

if [ -z "$PASSPHRASE" ]; then
  echo "PASSPHRASE is not configured"
  exit 1
fi

if [ -z "$USER" ]; then
  echo "PASSPHRASE is not configured"
  exit 1
fi

if [ -z "$FQDN" ]; then
  echo "PLATFORM_URL is not configured"
  exit 1
fi

PLATFORM_URL="https://$FQDN"

export CMD=""

if [ -z "$1" ]; then
  echo "usage: node <service> <verb>-<noun> <args>"
  exit 1
fi

if [ $1 == "skill" ]; then
    export CMD="skill"
fi

if [ $1 == "node" ]; then
    export CMD="node"
fi

if [ $1 == "register" ]; then
    export CMD="register"
fi

if [ -z "$CMD" ]; then
  echo "$1 is Invalid service"
  echo "Valid options:"
  echo "skill"
  echo "node"
  echo "register"
  exit 1
fi

/opt/demo/node_$CMD "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
