resources:
  - type: package 
    name: 'httpd'

  - type: service 
    name: httpd
    actions: 
      - enable
      - start

  - type: template 
    name: '/var/www/html/index.html' 
    source: 'index.html.erb'
