name 'target-mode-helper'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures target-mode-helper'
version '0.1.0'
chef_version '>= 16.0'
